baseURL = "http://localhost:8081"
languageCode = "en-us"
title = "From Mountains to Deep Seas"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-105570372-3"
theme = "conference"
enableRobotsTXT = true

[params]
  copyright= "Copyright (c) 2017, DMAD; all rights reserved."
  latitude = "41.9192077"
  longitude = "19.2158175"
  address = """<strong>Hotel Albatros</strong>
      <br>Steva Djakonovica bb
      <br>85360 Ulcinj
      <br>Montenegro
      <br>
  """
  DefaultDescription = "Ruffords Conference about developing a transboundary conservation network from mountains to deep seas. By DMAD, NHAM and the Montenegro Dolphin Project"
  author = "Lasse Capel"
  acceptAbstracts = true
  googleMapsApiKey = "AIzaSyCwOAT_sC03FGB3Ctq9cmtbULGu2zeKwwA"


[params.jumbotron]
  subtitle= "Research & Conservation Beyond Boundaries"
  jumbotroImage="img/img-jumbotron-bg.jpg"
  date = "February 3â€“6, 2018"
  location= "Montenegro"

[params.form]
  title = "Send your abstract"
  apiToken= "66e16fef2c878cce980c10f982e9904a"

[params.partners]
    enable = true
    # All testimonipartnersals are defined in their own files. You can find example items
    # at 'exampleSite/data/partners'.
    # For more informtion take a look at the README.
    title = "Partners"
    subtitle = "We would like to warmly thank all the partners and supporters which have made this conference possible."

[params.speakers]
  enable = true
  title= "Speakers"

[params.schedule]
  enable = false

[params.cta]
  name = "Send your abstract"
  url  = "/#section-abstract"
  scroll = true

[params.livestream]
  enable = false
  livestream = "GKaSpZbCDZw"


[menu]

[[menu.main]]
  name = "Speakers"
  url  = "/#section-speaker"
  weight = 1

[[menu.main]]
  name = "Venue"
  url ="/#section-venue"
  weight = 2

[[menu.main]]
  name = "Contact"
  url ="/information#contact"
  weight = 3

[[menu.pages]]
  name = "Home"
  url  = "/"
  weight = 1

[[menu.pages]]
  name = "Abstract"
  url  = "/abstract/"
  weight = 2

[[menu.pages]]
  name = "Information"
  url  = "/Information/"
  weight = 3
