baseURL = "http://localhost:8081"
languageCode = "en-us"
title = "From Mountains to Deep Seas"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-105570372-3"
theme = "conference"
enableRobotsTXT = true

[params]
  copyright= "Copyright (c) 2017, DMAD; all rights reserved."
  latitude = "41.9192077"
  longitude = "19.2158175"
  address = """<strong>Hotel Albatros</strong>
      <br>Steva Djakonovica bb
      <br>85360 Ulcinj
      <br>Montenegro
      <br>
  """
  description = "Conference about developing a transboundary conservation network from mountains to deep seas"
  author = "Lasse Capel"
  acceptAbstracts = true

[params.jumbotron]
  subtitle= "Developing Transboundary Conservation"
  jumbotroImage="img/img-jumbotron-bg.jpg"
  date = "February 3â€“6, 2018"
  location= "Montenegro"

[params.form]
  title = "Send your abstract"

[params.partners]
    enable = true
    # All testimonipartnersals are defined in their own files. You can find example items
    # at 'exampleSite/data/partners'.
    # For more informtion take a look at the README.
    title = "Partners"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.speakers]
  enable = true
  title= "Speakers"

[params.schedule]
  enable = false

[params.cta]
  name = "Send your abstract"
  url  = "/#section-abstract"
  scroll = true

[params.livestream]
  enable = false
  livestream = "GKaSpZbCDZw"


[menu]
# Main menu
[[menu.main]]
  name = "Home"
  url  = "/"
  weight = 1

[[menu.main]]
  name = "Speakers"
  url  = "/#section-speaker"
  weight = 2

[[menu.main]]
  name = "Partners"
  url = "/#section-partner"
  weight = 5

[[menu.main]]
  name = "Venue"
  url ="/#section-venue"
  weight = 6

[[menu.pages]]
    name = "Information"
    url  = "/Information/"
    weight = 1

[[menu.pages]]
    name = "Abstract"
    url  = "/contact/"
    weight = 8
    bla="bla"
